server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        jdbc:
          batch_size: 100
    database-platform: org.hibernate.dialect.MySQL57Dialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tech_local?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: tech_local
    password: local!32

  redis:
    host: localhost
    port: 6379

security:
  jwt:
    token:
      secret-key: tech-blog-hub-secret-key
      access-token-expire-length: 3600000 # 1 hour for access token
      refresh-token-expire-length: 1209600000 # 2 weeks for refresh token

kakao:
  auth:
    token-uri: https://kauth.kakao.com/oauth/token
    client-id: f7ef47fe00d9534eb077f71acd3c48e0
    redirect-uri: http://localhost:8080/kakao/callback

  user:
    profile-uri: https://kapi.kakao.com/v2/user/me

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.type.descriptor.sql: trace

rss:
  cron: "0 * * * * *"


springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match:
    - /api/**