server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        jdbc:
          batch_size: 100
    database-platform: org.hibernate.dialect.MySQL57Dialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?rewriteBatchedStatements=true
    username: root
    password: root132!

security:
  jwt:
    token:
      secret-key: atdd-secret-key
      expire-length: 3600000

kakao:
  auth:
    token-uri: https://kauth.kakao.com/oauth/token
    client-id: tech-blog-hub-client
    redirect-uri: /api/auth/kakao/callback

  user:
    profile-uri: https://kapi.kakao.com/v2/user/me

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.type.descriptor.sql: trace

rss:
  cron: "0 * * * * *"